{{- if not .Values.postgresCredsExistingSecrets.username.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgres-user
type: Opaque
data:
  username: {{ .Values.postgresCreds.username | b64enc }}
{{- end }}
---
{{- if not .Values.postgresCredsExistingSecrets.password.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgres-password
type: Opaque
data:
  password: {{ .Values.postgresCreds.password | b64enc }}
{{- end }}