apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgrest-operator.fullname" . }}
  labels:
    {{- include "postgrest-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "postgrest-operator.selectorLabels" . | nindent 4 }}