{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
type: Opaque
data:
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc }}
  POSTGRES_URI_ARGS: {{ .Values.postgres.uri_args | b64enc }}
  POSTGRES_CLOUD_PROVIDER: {{ .Values.postgres.cloud_provider | b64enc }}
  POSTGRES_DEFAULT_DATABASE: {{ .Values.postgres.default_database | b64enc }}
  {{- if not .Values.postgresCredsExistingSecrets }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASS: {{ .Values.postgres.password | b64enc }}
  {{- end  -}}
{{- end -}}