# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "core.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.solr.enabled }}
      initContainers:
        - name: wait-solr
          image: {{ .Values.solr.collection.initialize.image }}
          command: ["/bin/sh", "-c"]
          args:
          {{- if not .Values.solr.collection.initialize.enabled }}
            - until [ "$(curl -s -w '%{http_code}' -o /dev/null "{{ .Values.solr.url }}/admin/info/health")" -eq 200 ]; do echo "waiting for solr to be ready"; sleep 5; done
          {{- else }}
            - until [ "$(curl --user admin:$SOLR_ADMIN_PWD -s -w '%{http_code}' -o /dev/null "{{ .Values.solr.url }}/admin/info/health")" -eq 200 ]; do echo "waiting for solr to be ready"; sleep 5; done
          env:
            - name: "SOLR_ADMIN_PWD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.solr.collection.initialize.securityJsonSecret }}
                  key: admin
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.sts.enabled }}
            - name: DB_CREDENTIALS_USER
              {{- if and .Values.sts.client.existingSecret.name .Values.sts.client.existingSecret.usernameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sts.client.existingSecret.name }}
                  key: {{ .Values.sts.client.existingSecret.clientIdKey }}
              {{- else }}
              value: {{ .Values.sts.client.clientId }}
              {{- end }}
            - name: DB_CREDENTIALS_PASSWORD
              {{- if and .Values.sts.client.existingSecret.name .Values.sts.client.existingSecret.passwordKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sts.client.existingSecret.name }}
                  key: {{ .Values.sts.client.existingSecret.clientSecretKey}}
              {{- else }}
              value: {{ .Values.sts.client.clientSecret }}
              {{- end }}
          {{- end }}
          {{- if .Values.s3.dynamicCreds.enabled }}
            - name: MINIO_CREDENTIALS_ACCESS_KEY
            {{- if and .Values.s3.existingSecret.name .Values.s3.existingSecret.accessKeyKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret.name }}
                  key: {{ .Values.s3.existingSecret.accessKeyKey }}
            {{- else }}
              value: {{ .Values.s3.accessKey }}
            {{- end }}
            - name: MINIO_CREDENTIALS_SECRET_KEY
            {{- if and .Values.s3.existingSecret.name .Values.s3.existingSecret.secretKeyKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret.name }}
                  key: {{ .Values.s3.existingSecret.secretKeyKey }}
            {{- else }}
              value: {{ .Values.s3.secretKey }}
            {{- end }}
          {{- else }}
            - name: AWS_ACCESS_KEY
            {{- if and .Values.s3.existingSecret.name .Values.s3.existingSecret.accessKeyKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret.name }}
                  key: {{ .Values.s3.existingSecret.accessKeyKey }}
            {{- else }}
              value: {{ .Values.s3.secretKey }}
            {{- end }}
            - name: AWS_SECRET_KEY
            {{- if and .Values.s3.existingSecret.name .Values.s3.existingSecret.secretKeyKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret.name }}
                  key: {{ .Values.s3.existingSecret.secretKeyKey }}
            {{- else }}
              value: {{ .Values.s3.secretKey }}
            {{- end }}
          {{- end }}
            - name: JDBC_USER
              {{- if and .Values.postgres.credentials.existingSecret.name .Values.postgres.credentials.existingSecret.usernameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.credentials.existingSecret.name }}
                  key: {{ .Values.postgres.credentials.existingSecret.usernameKey }}
              {{- else }}
              value: {{ .Values.postgres.credentials.username }}
              {{- end }}
            - name: JDBC_PASS
              {{- if and .Values.postgres.credentials.existingSecret.name .Values.postgres.credentials.existingSecret.passwordKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.credentials.existingSecret.name }}
                  key: {{ .Values.postgres.credentials.existingSecret.passwordKey }}
              {{- else }}
              value: {{ .Values.postgres.credentials.password }}
              {{- end }}
            {{- if .Values.authentication.openId.enabled }}
            - name: DH_AUTH_OIDC_CLIENT_ID
              {{- if .Values.authentication.openId.externalSecret.name  }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authentication.openId.externalSecret.name }}
                  key: {{ .Values.authentication.openId.externalSecret.key }}
              {{- else}}
              value: {{ .Values.authentication.openId.oidcClientId }}
              {{- end }}
            {{- end }}
            - name: JWT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-auth-creds
                  key: clientId
            - name: JWT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-auth-creds
                  key: clientSecret
            {{- if .Values.solr.collection.initialize.enabled }}
            - name: SOLR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.solr.collection.initialize.securityJsonSecret }}
                  key: user
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "core.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if and .Values.keystore.existingSecret.secretName .Values.keystore.keystorePath }}
            - name: keystore
              mountPath: "{{ .Values.keystore.keystorePath }}/{{ .Values.keystore.existingSecret.keyName }}"
              subPath: {{ .Values.keystore.existingSecret.keyName }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if and .Values.keystore.existingSecret.secretName .Values.keystore.keystorePath }}
        - name: keystore
          secret:
            secretName: {{ .Values.keystore.existingSecret.secretName }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
