apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.fullname" . }}-rabbitmq-creds
type: Opaque
data:
  username: {{ .Values.events.rabbitmq.credentials.username | b64enc | quote }}
  password: {{ .Values.events.rabbitmq.credentials.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: core-auth-creds
type: Opaque
data:
  clientId: {{ .Values.coreAuthCreds.clientId | b64enc }}
  clientSecret: {{ .Values.coreAuthCreds.clientSecret | b64enc }}
