# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: core-auth-creds
type: Opaque
data:
  clientId: {{ .Values.coreAuthCreds.clientId | b64enc }}
  clientSecret: {{ .Values.coreAuthCreds.clientSecret | b64enc }}
