# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

{{ if and .Values.solr.collection.initialize.enabled .Values.solr.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-init-config
data:
  solr.sh: |
    #!/bin/sh
    curl --user "admin:$SOLR_ADMIN_PWD" -s "{{ .Values.solr.url }}/admin/collections?action=CREATE&name={{ .Values.solr.collection.name }}&numShards=1&replicationFactor=1&maxShardsPerNode=1&collection.configName=_default"
{{- end }}
