# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

{{ if and .Values.solr.collection.initialize.enabled .Values.solr.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-solr
          image: {{ .Values.solr.collection.initialize.image }}
          command: ["/bin/sh", "-c"]
          args: 
            - until [ "$(curl --user admin:$SOLR_ADMIN_PWD -s -w '%{http_code}' -o /dev/null "{{ .Values.solr.url }}/admin/info/health")" -eq 200 ]; do echo "waiting for solr to be ready"; sleep 5; done
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: "SOLR_ADMIN_PWD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.solr.collection.initialize.securityJsonSecret }}
                  key: admin
      containers:
        - name: solr-init-job
          image: {{ .Values.solr.collection.initialize.image }}
          command: ["/bin/sh", "/script/solr.sh"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
          - name: init-config
            mountPath: /script
          env:
            - name: "SOLR_ADMIN_PWD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.solr.collection.initialize.securityJsonSecret }}
                  key: admin
      restartPolicy: Never
      volumes:
        - name: init-config
          configMap:
            name: solr-init-config
{{- end }}
