apiVersion: v2
name: dremio-rest-server-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "1.0.3"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
