apiVersion: v2
name: platform
description: An open-source platform for interoperability of data and services, built by integrating several open-source projects to manage, elaborate, expose and serve data through modern standards.
type: application
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
version: "0.9.0"
appVersion: "0.9.0"
dependencies:
- name: argo-workflows
  version: "0.45.1"
  repository: https://argoproj.github.io/argo-helm
  condition: argo-workflows.enabled
- name: apigw-operator
  version: "0.1.8"
  repository: https://tn-aixpa.github.io/platform/
  condition: apigw-operator.enabled
- name: coder
  version: "2.12.0"
  repository: https://helm.coder.com/v2
  condition: coder.enabled
- name: core
  version: "0.3.1"
  repository: https://tn-aixpa.github.io/platform/
  condition: core.enabled
- name: kubernetes-resource-manager
  version: "0.2.6"
  repository: https://tn-aixpa.github.io/platform/
  condition: kubernetes-resource-manager.enabled
- name: dremio-rest-server-operator
  version: "0.1.5"
  repository: https://tn-aixpa.github.io/platform/
  condition: dremio-rest-server-operator.enabled
- name: docker-registry
  version: "2.2.2"
  repository: "https://helm.twun.io"
  condition: docker-registry.enabled
- name: ext-postgres-operator
  version: "1.2.6"
  repository: https://tn-aixpa.github.io/platform/
  condition: ext-postgres-operator.enabled
- name: minio
  repository: "https://charts.min.io/"
  version: "5.1.0"
  condition: minio.enabled
- name: postgres-operator
  version: "1.11.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  condition: postgres-operator.enabled
  tags:
    - operator
- name: postgrest-operator
  version: "0.1.7"
  repository: https://tn-aixpa.github.io/platform/
  condition: postgrest-operator.enabled
- name: template-controller
  version: "0.2.5"
  repository: https://kluctl.github.io/charts
  condition: template-controller.enabled
  tags:
    - operator
- name: solr-operator
  version: "0.8.1"
  repository: https://solr.apache.org/charts
  condition: solr-operator.enabled
  tags:
    - operator
- name: solr
  version: "0.8.1"
  repository: https://solr.apache.org/charts
  condition: solr.enabled
- name: minio-operator
  version: "0.1.5"
  repository: https://tn-aixpa.github.io/platform/
  condition: minio-operator.enabled
