# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.global.basicAuth.username .Values.global.basicAuth.password -}}
apiVersion: v1
data:
  auth: {{ htpasswd .Values.global.basicAuth.username .Values.global.basicAuth.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.basicAuth.secretName }}
{{- end }}
