# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.coder.enabled ( index .Values "postgres-operator" "databases" "coder" "enabled" ) -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: coder-postgres-cluster
spec:
  teamId: "coder"
  volume:
    size: {{ index .Values "postgres-operator" "databases" "coder" "volume" "size" }}
  numberOfInstances: 1
  users:
    coderadmin:
    - superuser
    - createdb
    coder: []
  databases:
    coder: coder
  postgresql:
    version: "15"
  resources:
  {{- toYaml ( index .Values "postgres-operator" "databases" "coder" "resources" ) | nindent 4 }}
{{- end }}
