# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.minio.enabled -}}
apiVersion: v1
data:
  digitalhubUser: {{ .Values.global.minio.digitalhubUser | b64enc }}
  digitalhubPassword: {{ .Values.global.minio.digitalhubPassword | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.minio.digitalhubUserSecret }}
type: Opaque
{{- end }}
