# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.minio.enabled -}}
apiVersion: v1
data:
  accesskey: {{ .Values.global.minio.argoUser | b64enc }}
  secretkey: {{ .Values.global.minio.argoPassword | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.minio.argoSecret }}
type: Opaque
{{- end }}
