# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if not .Values.solr.useExistingSecurityJson -}}
apiVersion: v1
data:
  admin: {{ .Values.solr.creds.admin.password | b64enc}}
  solr: {{ .Values.solr.creds.solr.password | b64enc }}
  user: {{ .Values.solr.creds.user.password | b64enc }}
  security.json: {{ tpl (.Files.Get "confs/solr/security.json") . | b64enc}}
kind: Secret
metadata:
  name: {{ .Values.solr.solrOptions.security.bootstrapSecurityJson.name }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.solr.creds.k8sOper.password | b64enc }}
  username: azhzLW9wZXI=
kind: Secret
metadata:
  name: {{ .Values.solr.solrOptions.security.basicAuthSecret }}
type: kubernetes.io/basic-auth
{{- end }}
