apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: azurefile-csi-driver
spec:
  clusterSelector:
    matchLabels:
      csi: azure
  repoURL: https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts
  chartName: azurefile-csi-driver
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    controller:
      runOnControlPlane: true
      replicas: 1