apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: azuredisk-csi-driver
spec:
  clusterSelector:
    matchLabels:
      cloud-provider: azure
  repoURL: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
  chartName: azuredisk-csi-driver
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
          controller:
            runOnControlPlane: true
