apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    kubeProxyReplacement: "true"
    k8sServiceHost: {{ .Cluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .Cluster.spec.controlPlaneEndpoint.port }}
    hubble:
      relay:
        enabled: true
      ui:
        enabled: "true"
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["{{ index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 }}"]
        clusterPoolIPv4MaskSize: 24 
    extraArgs:
      - "--mtu=1400"
    gatewayAPI:
      enabled: true