apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: metrics-server
spec:
  clusterSelector:
    matchLabels:
      cloud-provider: azure
  repoURL: https://kubernetes-sigs.github.io/metrics-server/
  chartName: metrics-server
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
    args:
      - --kubelet-insecure-tls