apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
 name: storageclasses
spec:
 strategy: "ApplyOnce"
 clusterSelector:
   matchLabels:
     cloud-provider: azure
 resources:
   - name: disk-storageclass
     kind: ConfigMap
   - name: fileshare-storageclass
     kind: ConfigMap