# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  ENABLE_TLS: {{ .Values.deployment.tls.enabled | quote }}
  TLS_SECRET_NAME: {{ .Values.deployment.tls.wildcardCertSecretName }}
  INGRESS_CLASS_NAME: {{ .Values.deployment.ingressClassName }}