{{ if .Values.namespaceValues.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "apigw-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "apigw-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "apigw-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}