{{- if ( index .Values "template-controller" "objectTemplate" "enabled" ) }}
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: {{ include "platform.fullname" . }}-common-creds-transformer
spec:
  serviceAccountName: secret-transformer
  prune: true
  matrix:
    - name: postgressecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: platform-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do
    - name: miniosecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: {{ .Values.global.minio.platformUserSecret }}
    - name: coresecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: core-auth-creds
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "platform-common-creds"
      stringData:
        POSTGRES_USER: "{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}"
        POSTGRES_PASSWORD: "{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}"
        AWS_ACCESS_KEY_ID: "{{ "{{" }} matrix.miniosecret.data.platformUser | b64decode {{ "}}" }}"
        AWS_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.miniosecret.data.platformPassword | b64decode {{ "}}" }}"
        JUPYTERLAB_S3_ACCESS_KEY_ID: "{{ "{{" }} matrix.miniosecret.data.platformUser | b64decode {{ "}}" }}"
        JUPYTERLAB_S3_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.miniosecret.data.platformPassword | b64decode {{ "}}" }}"
        POSTGRES_URL: "postgresql://{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}:{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}@database-postgres-cluster:5432/platform"
        JWT_CLIENT_ID: "{{ "{{" }} matrix.coresecret.data.clientId | b64decode {{ "}}" }}"
{{- end }}
