{{- if ( index .Values "postgres-operator" "databases" "platform" "enabled" ) }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: database-postgres-cluster
spec:
  teamId: "platform"
  volume:
    size: {{ index .Values "postgres-operator" "databases" "platform" "volume" "size" }}
  numberOfInstances: 1
  users:
    platformadmin:
    - superuser
    - createdb
  postgresql:
    version: "15"
  preparedDatabases:
    platform:
      defaultUsers: true
      schemas:
        public:
          defaultUsers: true
      extensions:
        timescaledb: public
        postgis: public
        vector: public
  resources:
  {{- toYaml ( index .Values "postgres-operator" "databases" "platform" "resources" ) | nindent 4 }}
{{- end }}
