# Delete all resources
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
rules:
  - apiGroups: ["acid.zalan.do"]
    resources: ["postgresqls"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "persistentvolumeclaims","pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments" ]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["solr.apache.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "platform.labels" .  | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: delete-resources
subjects:
  - name: delete-resources
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-solr
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-1"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: delete-solr
      labels:
        {{- include "platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: delete-resources
      containers:
        - name: delete-solr
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args: ["-c", "kubectl -n {{ .Release.Namespace }} delete solrclouds --all && sleep 2m"]
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12}}
            readOnlyRootFilesystem: {{ .Values.jobs.delete.securityContext.readOnlyRootFilesystem }}
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-postgres-databases
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "3"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: delete-postgres-databases
      labels:
        {{- include "platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: delete-resources
      containers:
        - name: delete-postgres-databases
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args: ["-c", "kubectl -n {{ .Release.Namespace }} delete postgresql --all && sleep 1m"]
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12}}
            readOnlyRootFilesystem: {{ .Values.jobs.delete.securityContext.readOnlyRootFilesystem }}
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-coder
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: delete-coder
      labels:
        {{- include "platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: delete-resources
      containers:
        - name: delete-coder
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args: ["-c", "kubectl -n {{ .Release.Namespace }} delete statefulsets,deploy,svc,cm -l app.kubernetes.io/part-of=coder && kubectl -n {{ .Release.Namespace }} delete --all pvc && kubectl -n {{ .Release.Namespace }} delete --all ingresses && sleep 1m"]
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12}}
            readOnlyRootFilesystem: {{ .Values.jobs.delete.securityContext.readOnlyRootFilesystem }}
      restartPolicy: OnFailure
---
{{- $resource := list -}}
{{- range $k, $v := .Values.global.cleanup }}
{{- if $v }}
{{- $resource = append $resource $k -}}
{{- end }}
{{- end }}
{{- if gt (len $resource) 0 -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-pvc-ingress
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "3"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: delete-pvc-ingress
      labels:
        {{- include "platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: delete-resources
      containers:
        - name: delete-pvc-ingress
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args: ["-c", "{{ range $resource }}kubectl -n {{ $.Release.Namespace }} delete --all {{ . }} && {{ end }} sleep 1m"]
      restartPolicy: OnFailure
{{- end }}
