{{- if and .Values.global.registry.username .Values.global.registry.password .Values.global.registry.email }}
apiVersion: v1
data:
  .dockerconfigjson: {{ tpl (.Files.Get "confs/.dockerconfigjson") . | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.registry.secretName }}
type: kubernetes.io/dockerconfigjson
{{- end }}