# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - docker-registry=https://helm.twun.io
  #- platform=https://scc-digitalhub.github.io/digitalhub/
  - zalando=https://opensource.zalando.com/postgres-operator/charts/postgres-operator
helm-extra-args: --timeout 600s
excluded-charts: 
  - coder
  - mlrun
  - mlrun-ce
  - nakamasato-mysql-operator
  - ext-postgres-operator
additional-commands:
  - sh -ec "if [ -f '{{ .Path }}/ci/lint.sh' ]; then shellcheck '{{ .Path }}/ci/lint.sh'; bash '{{ .Path }}/ci/lint.sh'; fi"
  # - helm unittest --helm3 --strict --file unittests/*.yaml --file 'unittests/**/*.yaml' {{ .Path }}
