# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  DRS_IMAGE: {{ .Values.conf.drsImage }}
  DRS_IMAGE_TAG: {{ .Values.conf.drsImageTag }}
  DRS_SERVICE_TYPE: {{ .Values.conf.drsServiceType }}