{{- if .Values.coder.enabled }}
apiVersion: v1
data:
  username: {{ .Values.coder.username | b64enc }}
  password: {{ .Values.coder.password | b64enc }}
  email: {{ .Values.coder.email | b64enc }}
kind: Secret
metadata:
  name: coder-user
type: Opaque
{{- end }}
