{{- if .Values.coder.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: coder-postgresql-creds
  annotations:
    "helm.sh/hook": post-install, post-upgrade
type: Opaque
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "coder.coder-postgres-cluster.credentials.postgresql.acid.zalan.do") -}}
{{- if $secret -}}
{{- $username := (index $secret.data "username") | b64dec }}
{{- $password := (index $secret.data "password") | b64dec }}
  uri: {{ printf "postgres://%s:%s@coder-postgres-cluster:5432/coder" $username $password | b64enc }}
{{- end -}}
{{- end }}