{{- if .Values.coder.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-additional-workspace-perms
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-additional-workspace-perms
subjects:
- kind: ServiceAccount
  name: {{ .Values.coder.coder.serviceAccount.name | quote }}
{{- end }}