apiVersion: v2
name: apigw-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.8
appVersion: "1.1.2"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
