apiVersion: v2
name: postgrest-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.7
appVersion: "2.0.5"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
