# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-resource-manager.fullname" . }}
  labels:
    {{- include "kubernetes-resource-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      {{ printf "%s: %s" "nodePort" (.Values.service.nodePort) }}
      {{- end }}
  selector:
    {{- include "kubernetes-resource-manager.selectorLabels" . | nindent 4 }}
