# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.coder.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-init
data:
  init.sh: | {{- tpl (.Files.Get "confs/coder/init.sh") . | nindent 4 }}
  upgrade.sh: | {{- tpl (.Files.Get "confs/coder/upgrade.sh") . | nindent 4 }}
{{- end }}
