# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.coder.enabled -}}
apiVersion: v1
data:
  username: {{ .Values.coder.username | b64enc }}
  password: {{ .Values.coder.password | b64enc }}
  email: {{ .Values.coder.email | b64enc }}
kind: Secret
metadata:
  name: coder-user
type: Opaque
{{- end }}
