# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.coder.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-custom-template
data:
{{ (.Files.Glob "confs/coder/*main.tf").AsConfig | indent 2 }}
{{- end }}
