apiVersion: v1
data:
  cluster-issuer-dns.yaml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod-dns
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ${EMAIL}
        privateKeySecretRef:
          name: letsencrypt-prod-dns
        solvers:
        - dns01:
            azureDNS:
              managedIdentity:
                resourceID: "${MANAGED_IDENTITY_RESOURCE_ID}"
              subscriptionID: "${SUBSCRIPTION_ID}"              
              resourceGroupName: "${RESOURCE_GROUP}"
              hostedZoneName: ${HOSTED_ZONE}
              environment: AzurePublicCloud
kind: ConfigMap
metadata:
  name: cluster-issuer-dns