apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
 name: gateway-wildcard-services-https
spec:
 strategy: "Reconcile"
 clusterSelector:
   matchLabels:
      cloud-provider: azure
      app: platform
      env: test
 resources:
   - name: gateway-wildcard-services-https
     kind: ConfigMap
