apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: kube-prometheus-stack
spec:
  clusterSelector:
    matchLabels:
      app: platform
      env: test
      monitoring: enabled
  repoURL: https://prometheus-community.github.io/helm-charts
  chartName: kube-prometheus-stack
  namespace: monitoring
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    grafana:
      adminPassword: ${GRAFANA_ADMIN_PASSWORD}
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
          - ${MONITORING_HOSTNAME}
        path: /
        tls:
          - hosts:
            - "${MONITORING_HOSTNAME}"
            secretName: platform-test-wildcard
    kubeEtcd:
      service:
        enabled: true
        port: 2382
        targetPort: 2382
      serviceMonitor:
        scheme: https
        caFile: /etc/prometheus/secrets/etcd-client/ca.crt
        certFile: /etc/prometheus/secrets/etcd-client/healthcheck-client.crt
        keyFile: /etc/prometheus/secrets/etcd-client/healthcheck-client.key
    prometheus:
      prometheusSpec:
        secrets:
          - etcd-client
        retention: 365d
        retentionSize: "120GB"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: 
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 128Gi
