apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
 name: wildcard-certificate-dns
spec:
 strategy: "Reconcile"
 clusterSelector:
   matchLabels:
      cloud-provider: azure
      app: platform
      env: test
 resources:
   - name: wildcard-certificate-dns
     kind: ConfigMap
