apiVersion: v1
data:
  wildcard-certificate-dns.yaml: |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: platform-test-wildcard
      namespace: ingress-nginx
    spec:
      dnsNames:
      - ${$DNS_NAME}
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt-prod-dns
      secretName: platform-test-wildcard
      secretTemplate:
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "platform-test,docker-registry,monitoring"  # Control destination namespaces
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "platform-test,docker-registry,monitoring" # Control auto-reflection namespaces
kind: ConfigMap
metadata:
  name: wildcard-certificate-dns
