{{ if not .Values.namespaceValues.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
{{ end }}
