apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  MINIO_ENDPOINT: "{{ .Values.minio.endpoint }}:{{ .Values.minio.endpointPort }}"
  MINIO_USE_SSL: "{{ if eq .Values.minio.protocol "https" }}true{{ else }}false{{ end }}"
  MINIO_EMPTY_BUCKET_ON_DELETE: {{ .Values.minio.emptyBucketOnDelete | quote }}
