{{ if .Values.namespaceValues.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-manager-role
rules:
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - minio.scc-digitalhub.github.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
{{ end }}
