name: Release Charts

on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Install changelog preset
        run: npm install -g @dslab/conventional-changelog-conventionalcommits-helm

      - name: Generate changelogs
        run: |
          for chart in charts/*; do
            tag=${chart//"charts/"/}
            if [ ${tag} != "platform" ]; then
              conventional-changelog -p @dslab/conventionalcommits-helm -i ${chart}/CHANGELOG.md -s -r 1 -t ${tag}- --commit-path ${chart}
            else
              conventional-changelog -p @dslab/conventionalcommits-helm -i ${chart}/CHANGELOG.md -s -r 1 -t ${tag}- -n .github/conventionalchangelog/config.json
            fi
          done

      - name: Set up Helm
        uses: Azure/setup-helm@v4
        with:
          version: v3.14.4

      # - name: Add dependency chart repos
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm repo add docker-registry https://helm.twun.io
      #     helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      #     helm repo add platform https://scc-digitalhub.github.io/digitalhub/
      #     helm repo add coder-v2 https://helm.coder.com/v2
      #     #temp remove after merging mlrun-ce
      #     helm repo add stable https://charts.helm.sh/stable
      #     helm repo add nuclio https://nuclio.github.io/nuclio/charts
      #     helm repo add v3io-stable https://v3io.github.io/helm-charts/stable
      #     helm repo add minio https://charts.min.io/
      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: false
          CR_RELEASE_NOTES_FILE: CHANGELOG.md
          CR_SKIP_EXISTING: true

      # see https://github.com/helm/chart-releaser/issues/183
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
          done
